# Generated by Django 4.2.3 on 2023-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0003_advertisments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisments',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
